Create Series and DataFrame

Create:

Pandas Series
DataFrame from dictionary
DataFrame from list

Concepts:

pd.Series()
pd.DataFrame()

In [1]:
import pandas as pd

In [2]:
sports_list=['Cricket','Football','Volleyball']
series=pd.Series(sports_list)
print(series)

0       Cricket
1      Football
2    Volleyball
dtype: object

In [3]:
data_matrix=[
    ['Liana', 14, 'Azamgarh'],
    ['Allia', 16, 'Gangoh'],
    ['Kendal', 15, 'Amroha']
]

df_from_list = pd.DataFrame(data_matrix, columns=['Name', 'Age', 'City'])
print(df_from_list)

     Name  Age      City
0   Liana   14  Azamgarh
1   Allia   16    Gangoh
2  Kendal   15    Amroha

Read and Write CSV Files

Perform:

Read CSV
Save CSV

Concepts:

pd.read_csv()
df.to_csv()

In [4]:
import pandas as pd
pi = pd.read_csv('data.csv')
print(pi.head())

  helloo world i am writing it now!!!
0             princess or queen iykyk

In [5]:
data_matrix=[
    ['Liana', 14, 'Azamgarh'],
    ['Allia', 16, 'Gangoh'],
    ['Kendal', 15, 'Amroha']
]
df_from_list = pd.DataFrame(data_matrix, columns=['Name', 'Age', 'City'])
print(df_from_list)
df_from_list.to_csv('data_matrix.csv')

     Name  Age      City
0   Liana   14  Azamgarh
1   Allia   16    Gangoh
2  Kendal   15    Amroha

Inspect Dataset

Find:

Shape
Columns
Data types
First/last rows

Concepts:

df.head()
df.tail()
df.info()
df.shape

In [6]:
import pandas as pd

student_data = {
    "Student Name": ["Aarav", "Ananya", "Vivaan", "Diya", "Kabir", "Meera", "Rohan", "Isha", "Arjun", "Sanya"],
    "Age": [23, 18, 18, 23, 20, 19, 19, 19, 23, 18],
    "City": ["Jaipur", "Delhi", "Lucknow", "Kolkata", "Mumbai", "Mumbai", "Delhi", "Hyderabad", "Hyderabad", "Jaipur"]
}
df = pd.DataFrame(student_data)
print(df)

  Student Name  Age       City
0        Aarav   23     Jaipur
1       Ananya   18      Delhi
2       Vivaan   18    Lucknow
3         Diya   23    Kolkata
4        Kabir   20     Mumbai
5        Meera   19     Mumbai
6        Rohan   19      Delhi
7         Isha   19  Hyderabad
8        Arjun   23  Hyderabad
9        Sanya   18     Jaipur

In [7]:
df.head()

  Student Name  Age     City
0        Aarav   23   Jaipur
1       Ananya   18    Delhi
2       Vivaan   18  Lucknow
3         Diya   23  Kolkata
4        Kabir   20   Mumbai

In [8]:
df.shape

(10, 3)

In [9]:
df.tail()

  Student Name  Age       City
5        Meera   19     Mumbai
6        Rohan   19      Delhi
7         Isha   19  Hyderabad
8        Arjun   23  Hyderabad
9        Sanya   18     Jaipur

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student Name  10 non-null     object
 1   Age           10 non-null     int64
 2   City          10 non-null     object
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

Select Rows and Columns

Perform:

Single column selection
Multiple column selection
Row selection

Concepts:

loc[]
iloc[]

In [11]:
sub_table = df[['Student Name', 'City']]
print(sub_table)

  Student Name       City
0        Aarav     Jaipur
1       Ananya      Delhi
2       Vivaan    Lucknow
3         Diya    Kolkata
4        Kabir     Mumbai
5        Meera     Mumbai
6        Rohan      Delhi
7         Isha  Hyderabad
8        Arjun  Hyderabad
9        Sanya     Jaipur

In [12]:
sub_loc=df.iloc[0]
row=df.iloc[:3]
print(row)
print('-'*20)
print(sub_loc)

  Student Name  Age     City
0        Aarav   23   Jaipur
1       Ananya   18    Delhi
2       Vivaan   18  Lucknow
--------------------
Student Name     Aarav
Age                 23
City            Jaipur
Name: 0, dtype: object

Handle Missing Values

Perform:

Detect null values
Fill missing values
Drop missing values

Concepts:

isnull()
fillna()
dropna()

In [13]:
df.isnull()

   Student Name    Age   City
0         False  False  False
1         False  False  False
2         False  False  False
3         False  False  False
4         False  False  False
5         False  False  False
6         False  False  False
7         False  False  False
8         False  False  False
9         False  False  False

In [14]:
clean_subset = df.dropna(subset=['City'])
print(clean_subset)

  Student Name  Age       City
0        Aarav   23     Jaipur
1       Ananya   18      Delhi
2       Vivaan   18    Lucknow
3         Diya   23    Kolkata
4        Kabir   20     Mumbai
5        Meera   19     Mumbai
6        Rohan   19      Delhi
7         Isha   19  Hyderabad
8        Arjun   23  Hyderabad
9        Sanya   18     Jaipur

Filter Data

Find:

Students scoring above 80
Employees with salary > 50000
Multiple conditions

Concepts:

Boolean indexing

Example:

df[df["Marks"] > 80]

In [15]:
age=df[df['Age']>20]
print(age)

  Student Name  Age       City
0        Aarav   23     Jaipur
3         Diya   23    Kolkata
8        Arjun   23  Hyderabad

Sorting and Ranking

Perform:

Sort by marks
Sort descending
Rank students

Concepts:

sort_values()
rank()

In [16]:
sort=df.sort_values(by='Age')
print(sort)

  Student Name  Age       City
1       Ananya   18      Delhi
2       Vivaan   18    Lucknow
9        Sanya   18     Jaipur
6        Rohan   19      Delhi
7         Isha   19  Hyderabad
5        Meera   19     Mumbai
4        Kabir   20     Mumbai
3         Diya   23    Kolkata
0        Aarav   23     Jaipur
8        Arjun   23  Hyderabad

In [17]:
sorted_high_to_low = df.sort_values(by='Age', ascending=False)
print(sorted_high_to_low)

  Student Name  Age       City
0        Aarav   23     Jaipur
3         Diya   23    Kolkata
8        Arjun   23  Hyderabad
4        Kabir   20     Mumbai
7         Isha   19  Hyderabad
5        Meera   19     Mumbai
6        Rohan   19      Delhi
1       Ananya   18      Delhi
2       Vivaan   18    Lucknow
9        Sanya   18     Jaipur

GroupBy Operations

Perform:

Department-wise salary average
Subject-wise marks average

Concepts:

groupby()
mean()
sum()
count()

In [18]:
import pandas as pd
data = {
    "Employee": ["Aarav", "Ananya", "Vivaan", "Diya", "Kabir", "Meera", "Rohan", "Isha", "Arjun", "Sanya"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT", "Finance", "HR", "IT"],
    "Salary": [85000, 60000, 90000, 75000, 65000, 80000, 88000, 72000, 62000, 92000],
    "Subject": ["Python", "Excel", "SQL", "Excel", "Excel", "Python", "Python", "SQL", "SQL", "Python"],
    "Marks": [88, 75, 92, 80, 85, 90, 78, 83, 89, 95]
}

df = pd.DataFrame(data)
print("Original Dataset:\n", df)

Original Dataset:
   Employee Department  Salary Subject  Marks
0    Aarav         IT   85000  Python     88
1   Ananya         HR   60000   Excel     75
2   Vivaan         IT   90000     SQL     92
3     Diya    Finance   75000   Excel     80
4    Kabir         HR   65000   Excel     85
5    Meera    Finance   80000  Python     90
6    Rohan         IT   88000  Python     78
7     Isha    Finance   72000     SQL     83
8    Arjun         HR   62000     SQL     89
9    Sanya         IT   92000  Python     95

In [19]:
dept_salary_avg = df.groupby('Department')['Salary'].mean()
print(dept_salary_avg)

Department
Finance    75666.666667
HR         62333.333333
IT         88750.000000
Name: Salary, dtype: float64

In [20]:
subject_marks_avg = df.groupby('Subject')['Marks'].mean()
print(subject_marks_avg)

Subject
Excel     80.00
Python    87.75
SQL       88.00
Name: Marks, dtype: float64

In [21]:
total_payroll = df.groupby('Department')['Salary'].sum()
print(total_payroll)

Department
Finance    227000
HR         187000
IT         355000
Name: Salary, dtype: int64

In [22]:
subject_count = df.groupby('Subject')['Employee'].count()
print(subject_count)

Subject
Excel     3
Python    4
SQL       3
Name: Employee, dtype: int64

Merge and Join DataFrames

Perform:

Inner join
Left join
Merge datasets

Concepts:

pd.merge()

In [23]:
import pandas as pd
students_df = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Name": ["Aarav", "Ananya", "Vivaan", "Diya"]
})
marks_df = pd.DataFrame({
    "StudentID": [101, 102, 103, 105],
    "Subject": ["Python", "Excel", "SQL", "Python"],
    "Marks": [88, 95, 79, 92]
})

In [24]:
inner_result = pd.merge(students_df, marks_df, on='StudentID', how='inner')
print(inner_result)

   StudentID    Name Subject  Marks
0        101   Aarav  Python     88
1        102  Ananya   Excel     95
2        103  Vivaan     SQL     79

In [25]:
left_result = pd.merge(students_df, marks_df, on='StudentID', how='left')
print(left_result)

   StudentID    Name Subject  Marks
0        101   Aarav  Python   88.0
1        102  Ananya   Excel   95.0
2        103  Vivaan     SQL   79.0
3        104    Diya     NaN    NaN